# stage 1 - Build
FROM node:18 AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

# stage 2 - Production
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app /app
# Create a non-root user to run the application
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

EXPOSE 3000

CMD [ "node", "app.js" ]