---
# tasks file for roles/docker
# 1. Install dependencies
- name: Install Docker dependencies
  dnf:
    name:
      - dnf-plugins-core
      - device-mapper-persistent-data
      - lvm2
    state: present
  tags: docker

# 2. Add Docker CE repository
- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"
  tags: docker

# 3. Install Docker
- name: Install Docker
  dnf:
    name: docker
    state: present
  tags: docker
  notify: Restart Docker

# 4. Start and enable Docker
- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: true
  tags: docker

# 5. Add deploy user to docker group
- name: Add deploy user to docker group
  user:
    name: deploy
    groups: docker
    append: true
  tags: docker

# 6. Install Docker Compose
- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v5.1.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  tags: docker

# 7. Login to Docker Hub
- name: Log in to Docker Hub
  community.docker.docker_login:
    username: "{{ vault_docker_username }}"
    password: "{{ vault_docker_password }}"
  become_user: deploy
  when: vault_docker_username is defined
  tags: docker

# 8. Pull image
- name: Pull application image
  community.docker.docker_image:
    name: "{{ docker_app_image }}"
    tag: "{{ docker_app_tag }}"
    source: pull
  tags: docker

# 9. Remove any container using this port
- name: Remove any container using this port
  shell: |
    docker ps -q --filter "publish={{ docker_app_port }}" | xargs -r docker rm -f
  ignore_errors: true
  tags: docker

# 10. Run new conatiner
- name: Run application container
  community.docker.docker_container:
    name: "{{ docker_app_name }}"
    image: "{{ docker_app_image }}:{{ docker_app_tag }}"
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - "{{ docker_app_port }}:{{ docker_container_port }}"
  tags: docker

# 11. Heath Check
- name: Wait for container to be healthy
  uri:
    url: "http://localhost:{{ docker_app_port }}"
    status_code: 200
  register: health_check
  retries: 10
  delay: 3
  until: health_check.status == 200
  tags: docker
